# Generated by Django 5.1.1 on 2025-01-15 16:31

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        VectorExtension()
    ]
