# Generated by Django 5.1.5 on 2025-01-19 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='demonstrators',
        ),
        migrations.RemoveField(
            model_name='module',
            name='organizers',
        ),
        migrations.RemoveField(
            model_name='module',
            name='students',
        ),
        migrations.CreateModel(
            name='ModuleMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Student', 'Student'), ('Demonstrator', 'Demonstrator'), ('Organizer', 'Organizer')], max_length=50)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='members',
            field=models.ManyToManyField(through='api.ModuleMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
