# Generated by Django 5.1.5 on 2025-01-15 23:26

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='embedding',
        ),
        migrations.RemoveField(
            model_name='module',
            name='html',
        ),
        migrations.CreateModel(
            name='ModuleEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_data', pgvector.django.vector.VectorField(dimensions=1536)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='api.module')),
            ],
        ),
    ]
