# Generated by Django 5.1.5 on 2025-01-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_module_embedding_remove_module_html_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleembedding',
            name='content',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
