# Generated by Django 5.1.5 on 2025-01-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_moduleembedding_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='course_id',
        ),
        migrations.AlterField(
            model_name='module',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
