# Generated by Django 5.1.5 on 2025-01-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_module_course_id_alter_module_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='url',
            field=models.URLField(max_length=300),
        ),
    ]
