# Generated by Django 5.1.5 on 2025-01-17 15:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_module_id_alter_module_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='organizers',
            field=models.ManyToManyField(blank=True, related_name='organized_modules', to=settings.AUTH_USER_MODEL),
        ),
    ]
