# Generated by Django 5.1.5 on 2025-01-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_module_organizers'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='module_icons/'),
        ),
    ]
