# Generated by Django 5.1.5 on 2025-01-17 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_module_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='icon',
        ),
    ]
