# Generated by Django 5.1.5 on 2025-01-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_module_demonstrators'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='enable_welcome_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='module',
            name='welcome_message',
            field=models.TextField(default='Welcome to the module chat!'),
        ),
    ]
