# Generated by Django 5.1.2 on 2024-10-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embeddings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='embedding',
        ),
        migrations.AddField(
            model_name='module',
            name='index_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
