# Generated by Django 5.1.2 on 2024-11-05 12:41

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embeddings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='embedding',
        ),
        migrations.AddField(
            model_name='module',
            name='html',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='index_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='modules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='module',
            name='url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
