# Generated by Django 5.1.2 on 2024-10-27 12:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embeddings', '0002_remove_module_embedding_module_index_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='modules', to=settings.AUTH_USER_MODEL),
        ),
    ]
