# Generated by Django 5.1.2 on 2024-10-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embeddings', '0004_chatlog_module_delete_faissindex_chatlog_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlog',
            name='bot_message',
            field=models.BooleanField(default=False),
        ),
    ]
